name: CI/CD Pipeline

permissions:
  contents: read
  packages: write
  id-token: write   

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compose
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Deploy stack
        env:
          COMPOSE_PROJECT_NAME: nginx-stack
        run: |
          docker-compose -f docker/compose.yml up -d
